services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    image: flight-disruption-recovery:latest
    container_name: flight-disruption-recovery
    ports:
      - "8080:8080"

    restart: always
